/**
 * default setting
 */

export default {
  hotkey: 'Control+2',
  sshReadyTimeout: 50000,
  scrollback: 3000,
  onStartSessions: [],
  fontSize: 16,
  fontFamily: 'JetBrains Mono, Fira Code, SF Mono, Menlo, Consolas, monospace',
  execWindows: 'System32/WindowsPowerShell/v1.0/powershell.exe',
  execMac: 'zsh',
  execLinux: 'bash',
  execWindowsArgs: [],
  execMacArgs: [],
  execLinuxArgs: [],
  enableGlobalProxy: false,
  disableConnectionHistory: false,
  disableTransferHistory: false,
  terminalBackgroundImagePath: '',
  terminalBackgroundFilterOpacity: 1,
  terminalBackgroundFilterBlur: 0,
  terminalBackgroundFilterBrightness: 1,
  terminalBackgroundFilterGrayscale: 0,
  terminalBackgroundFilterContrast: 1,
  terminalBackgroundText: '',
  terminalBackgroundTextSize: 48,
  terminalBackgroundTextColor: '#ffffff',
  terminalBackgroundTextFontFamily: 'Maple Mono',
  rendererType: 'canvas',
  terminalType: 'xterm-256color',
  keepaliveCountMax: 10,
  keyword2FA: 'verification code,otp,one-time,two-factor,2fa,totp,authenticator,duo,yubikey,security code,mfa,passcode',
  saveTerminalLogToFile: false,
  checkUpdateOnStart: true,
  cursorBlink: false,
  cursorStyle: 'block',
  useSystemTitleBar: false,
  opacity: 1,
  defaultEditor: '',
  terminalWordSeparator: './\\()"\'-:,.;<>~!@#$%^&*|+=[]{}`~ ?',
  confirmBeforeExit: false,
  initDefaultTabOnStart: false,
  screenReaderMode: false,
  autoRefreshWhenSwitchToSftp: false,
  addTimeStampToTermLog: false,
  sftpPathFollowSsh: false,
  keepaliveInterval: 10000,
  backspaceMode: '^?',
  showHiddenFilesOnSftpStart: true,
  terminalInfos: [
    'uptime',
    'cpu',
    'mem',
    'activities',
    'network',
    'disks'
  ],
  filePropsEnabled: [
    'name',
    'size',
    'modifyTime'
  ],
  hideIP: false,
  dataSyncSelected: 'all',
  nameAI: 'DeepSeek 运维助手',
  baseURLAI: 'https://api.deepseek.com',
  modelAI: 'deepseek-v4-flash',
  roleAI: '资深运维助手，基于证据解释命令、分析报错并给出可验证的排查步骤，使用 markdown 格式',
  apiPathAI: '/chat/completions',
  proxyAI: '',
  sessionLogPath: '',
  sshSftpSplitView: false,
  showCmdSuggestions: false,
  autoReconnectTerminal: true,
  startDirectoryLocal: '',
  allowMultiInstance: false,
  disableDeveloperTool: false,
  dragDropBehavior: 'ask'
}
