blank_issues_enabled: false
contact_links:
  - name: ⁉️ Need help with electermPlus?
    url: https://github.com/codezhangzj/electermPlus/discussions
    about: Please start a discussion before opening a bug.
